### ISSUE TITLE
Start number template with chosen number

### ISSUE THREAD

**Issue by alextoss** [segoja/mass-file-renamer#11]
Hello,

Is there a way to start the number template with a number we choose ?

The goal is to rename following files :
Dragon.Ball.E01
Dragon.Ball.E02
Dragon.Ball.E03
Dragon.Ball.E04
Dragon.Ball.E05
Dragon.Ball.E06
Dragon.Ball.E07
etc...

to
Dragon.Ball.E68
Dragon.Ball.E69
Dragon.Ball.E70
Dragon.Ball.E71
Dragon.Ball.E72
Dragon.Ball.E73
Dragon.Ball.E74
etc...

Thanks for your amazing app.

**Comment by segoja** [comment]
Hi @alextoss, 
The app doesn't support that currently, unfortunately. I think it's a useful feature so I'll work on it as soon as I can.

Thanks for using the app and for giving feedback.

**Comment by segoja** [comment]
New version [released](https://github.com/segoja/mass-file-renamer/releases/tag/v0.6.0) with the requested feature.

**Comment by segoja** [comment]
New version [released](https://github.com/segoja/mass-file-renamer/releases/tag/v0.6.1) with the requested feature.

**Comment by alextoss** [comment]
Thanks for your fast release !
