### ISSUE TITLE
[Bug] German umlauts removed

### ISSUE THREAD

**Issue by hrst** [segoja/mass-file-renamer#7]
Thanks for the app!

When using it on file which had a German umlaut in them (äöüÄÖÜ) the umlaut was removed (I used find and replace to rename the extension).

**Comment by segoja** [comment]
Hi, thanks for reporting! I'll release a fix for this bug along with other changes very soon.

**Comment by segoja** [comment]
New version released. I simplified the security checks to allow all kinds of characters except those not allowed by the filesystem. I hope it works.
