### ISSUE TITLE
[Feature Idea] Drag in folder -> all files from folder and subfolders are added to the list

### ISSUE THREAD

**Issue by hrst** [segoja/mass-file-renamer#8]
An awesome upgrade (imho of course) would be to be able to drag in a folder from the Windows Explorer, and it then automatically searches the folder and all subfolders (and their subfolders etc.) for files and just add them to the list. I solved this by searching for *.* in the explorer which works of course but I thought maybe you like the idea! Thanks in any case!

**Comment by segoja** [comment]
Hi! I really like the idea and I'm already working on it. It will be available in the next update.

**Comment by segoja** [comment]
New version released with the requested feature.
